import { setRequestLocale } from "next-intl/server";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function ProfileLayout(props: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const params = await props.params;

  const { locale } = params;

  const { children } = props;

  setRequestLocale(locale);
  return <div className="p-6">{children}</div>;
}
